alias cat="bat -p"
alias neovim="/opt/neovim/nvim.appimage"
alias nvim="/opt/neovim/nvim.appimage"
alias vim="/opt/neovim/nvim.appimage"
alias vi="/opt/neovim/nvim.appimage"
export VISUAL="/opt/neovim/nvim.appimage"
export EDITOR="/opt/neovim/nvim.appimage"
alias l="ls -lrth"
